apiVersion: v1
kind: Secret
metadata:
  name: dashboard-glpi-secret
  namespace: dashboard-glpi
type: Opaque
stringData:
  DASHBOARD_ADMIN: <DASHBOARD_ADMIN>
  DASHBOARD_PASSWORD: <DASHBOARD_PASSWORD>
  GLPI_USER_TOKEN: <GLPI_USER_TOKEN>
