apiVersion: v1
kind: Secret
metadata:
  name: dashboard-glpi-secret
  namespace: dashboard-glpi
type: Opaque
data:
  GLPI_USER_TOKEN: <GLPI_USER_TOKEN>
  OIDC_CLIENT_SECRET: <OIDC_CLIENT_SECRET>
  FLASK_SECRET_KEY: <FLASK_SECRET_KEY>
