apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-glpi-config
  namespace: dashboard-glpi
data:
  DASHBOARD_ENABLE_AUTHENTICATION: '<DASHBOARD_ENABLE_AUTHENTICATION>'
  GLPI_URL: '<GLPI_URL>'
  DEBUG_SEARCH_OPTIONS: '<DEBUG_SEARCH_OPTIONS>'
